#spring.application.name=eurekaserver


spring:
  application:
    name: eurekaserver
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms: 500