spring:
  application:
    name: author-service

server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# swagger-ui custom path
springdoc:
  swagger-ui:
  path: /swagger-ui.html