#spring.application.name=book-service
#server.port=8200

server:
  port: 8200

spring:
  application:
    name: book-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
